apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-rest-api
  template:
    metadata:
      labels:
        app: sample-rest-api
    spec:
      containers:
      - name: hello
        image: gcr.io/sample-rest-api/sample-rest-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-rest-api-service
spec:
  selector:
    app: sample-rest-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
